// Mock data for development and testing

export const mockContributions = [
  {
    id: "1",
    memberId: "1",
    amount: 500,
    contributionType: "Donation",
    description: "Annual membership contribution",
    contributionDate: "2024-01-15",
    status: "completed",
  },
  {
    id: "2",
    memberId: "1",
    amount: 250,
    contributionType: "Project Fund",
    description: "Community outreach program",
    contributionDate: "2024-02-20",
    status: "completed",
  },
  {
    id: "3",
    memberId: "1",
    amount: 100,
    contributionType: "Donation",
    description: "Disaster relief fund",
    contributionDate: "2024-03-10",
    status: "pending",
  },
]

export const mockPayments = [
  {
    id: "1",
    memberId: "1",
    amount: 150,
    paymentType: "Membership Fee",
    description: "2024 Annual Membership",
    paymentDate: "2024-01-01",
    status: "completed",
    paymentMethod: "Credit Card",
  },
  {
    id: "2",
    memberId: "1",
    amount: 50,
    paymentType: "Event Registration",
    description: "Annual Gala 2024",
    paymentDate: "2024-02-15",
    status: "completed",
    paymentMethod: "Bank Transfer",
  },
]

export const mockMembers = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john@rotary.com",
    position: "President",
    joinDate: "2020-01-15",
    status: "active",
    phone: "+63-917-123-4567",
    bio: "Passionate about community service",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane@rotary.com",
    position: "Vice President",
    joinDate: "2021-06-20",
    status: "active",
    phone: "+63-917-234-5678",
    bio: "Dedicated to making a difference",
  },
  {
    id: "3",
    firstName: "Robert",
    lastName: "Johnson",
    email: "robert@rotary.com",
    position: "Treasurer",
    joinDate: "2019-03-10",
    status: "active",
    phone: "+63-917-345-6789",
    bio: "Financial steward of the club",
  },
  {
    id: "4",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria@rotary.com",
    position: "Secretary",
    joinDate: "2022-05-05",
    status: "active",
    phone: "+63-917-456-7890",
    bio: "Keeping our club organized",
  },
]

export const mockBlogPosts = [
  {
    id: "1",
    memberId: "1",
    title: "Community Health Drive: Reaching 500+ Residents",
    slug: "community-health-drive",
    excerpt: "Our latest health initiative provided free medical checkups and consultations to over 500 community members in underserved areas.",
    content: "This month, our club launched an ambitious community health drive in partnership with local healthcare providers...",
    category: "Health",
    author: "Dr. John Doe",
    image: "/health-awareness-campaign.png",
    status: "published",
    publishedAt: "2024-03-15",
    createdAt: "2024-03-10",
  },
  {
    id: "2",
    memberId: "2",
    title: "Education First: 25 Scholars Graduate with Honors",
    slug: "scholarship-program-success",
    excerpt: "Celebrating the success of our scholarship program with a 100% graduation rate and outstanding academic achievements.",
    content: "Every year, our scholarship program transforms lives by providing educational opportunities to deserving students...",
    category: "Education",
    author: "Jane Smith",
    image: "/scholarship-program.jpg",
    status: "published",
    publishedAt: "2024-03-10",
    createdAt: "2024-03-05",
  },
  {
    id: "3",
    memberId: "1",
    title: "Green Initiative: 5,000 Trees Planted",
    slug: "tree-planting-initiative",
    excerpt: "Our environmental conservation project successfully planted 5,000 trees across 50 hectares, contributing to a greener future.",
    content: "Working together with the community, we've made significant strides in environmental conservation...",
    category: "Projects",
    author: "Maria Reyes",
    image: "/community-tree-planting.png",
    status: "published",
    publishedAt: "2024-03-08",
    createdAt: "2024-03-03",
  },
  {
    id: "4",
    memberId: "3",
    title: "Annual Gala 2024: A Night of Service and Celebration",
    slug: "annual-gala-2024",
    excerpt: "Join us in celebrating another successful year of community service at our Annual Gala event.",
    content: "This year's Annual Gala was a resounding success, bringing together members, partners, and community leaders...",
    category: "Events",
    author: "Robert Johnson",
    image: "/rotary-club-president.jpg",
    status: "published",
    publishedAt: "2024-03-05",
    createdAt: "2024-03-01",
  },
  {
    id: "5",
    memberId: "2",
    title: "Disaster Relief: Supporting 200+ Families",
    slug: "disaster-relief-effort",
    excerpt: "Our rapid response team provided emergency assistance to over 200 families affected by recent typhoon damage.",
    content: "When disaster strikes, our club mobilizes quickly to provide critical support to affected communities...",
    category: "Community Service",
    author: "Jane Smith",
    image: "/disaster-relief.jpg",
    status: "published",
    publishedAt: "2024-03-01",
    createdAt: "2024-02-25",
  },
  {
    id: "6",
    memberId: "4",
    title: "Women Empowerment: 50 New Entrepreneurs",
    slug: "women-entrepreneurs-program",
    excerpt: "Our microfinance and training program helped 50 women start their own businesses, increasing average income by 150%.",
    content: "Economic empowerment is at the heart of sustainable community development...",
    category: "Projects",
    author: "Maria Garcia",
    image: "/diverse-women-entrepreneurs.png",
    status: "published",
    publishedAt: "2024-02-28",
    createdAt: "2024-02-20",
  },
]

export const mockProjectReports = [
  {
    id: "1",
    memberId: "1",
    title: "School Renovation Project",
    description: "Renovated the local elementary school library",
    projectDate: "2024-02-20",
    impactSummary: "Successfully completed library renovation",
    beneficiariesCount: 250,
    hoursSpent: 40,
    status: "published",
    publishedAt: "2024-02-25",
  },
  {
    id: "2",
    memberId: "2",
    title: "Health Awareness Campaign",
    description: "Conducted health screening and awareness program",
    projectDate: "2024-03-10",
    impactSummary: "Screened 150 community members",
    beneficiariesCount: 150,
    hoursSpent: 24,
    status: "published",
    publishedAt: "2024-03-12",
  },
]

export const mockAttendance = [
  {
    id: "1",
    memberId: "1",
    eventName: "Weekly Club Meeting",
    eventDate: "2024-03-20",
    hoursVolunteered: 2,
    role: "Participant",
    notes: "Active participation in discussion",
  },
  {
    id: "2",
    memberId: "1",
    eventName: "Community Cleanup Drive",
    eventDate: "2024-03-15",
    hoursVolunteered: 4,
    role: "Team Lead",
    notes: "Led the cleanup team",
  },
  {
    id: "3",
    memberId: "1",
    eventName: "Scholarship Award Ceremony",
    eventDate: "2024-03-10",
    hoursVolunteered: 3,
    role: "Volunteer",
    notes: "Helped with event setup and coordination",
  },
]
